name: Get Variables

runs:
  using: "composite"
  steps:
    - name: Parse Forgejo payload
      shell: bash
      run: |
        PAYLOAD_JSON='${{ toJSON(github.event.client_payload) }}'
        FORGEJO_REF=$(echo "$PAYLOAD_JSON" | jq -r '.ref')
        if [ -z "$FORGEJO_REF" ]
        then
          FORGEJO_REF="master"
        fi

        echo "FORGEJO_REF=$FORGEJO_REF" >> $GITHUB_ENV
