name: Create Release

on:
  repository_dispatch:
    types: [master]

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.parse.outputs.ref }}
    steps:
      - name: Parse Forgejo payload
        id: parse
        uses: ./.github/workflows/parse

  build:
    name: Build
    needs: [parse]
    uses: https://github.com/Eden-CI/Workflow@master
    with:
      ref: ${{ needs.parse.outputs.ref }}
      build-id: 'eden-master'

  release:
    name: Create Release
    needs: [parse, build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Package artifacts nicely
        uses: Eden-CI/Workflow/util/pack/action.yml@master
        with:
          ref: ${{ needs.parse.outputs.ref }}

      - name: Generate changelog
        run: |
          # export FORGEJO_TOKEN=${{ secrets.FORGEJO_TOKEN }}
          export FORGEJO_REF=${{ needs.parse.outputs.ref }}
          ./body.sh > changelog.md

      - name: Delete Previous Release
        run: |
          gh release delete "${{ needs.parse.outputs.ref }}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag  -y
          sleep 5
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden Master - ${{ needs.parse.outputs.ref }}"
          tag_name: ${{ needs.parse.outputs.ref }}
          body_path: ./changelog.md
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*
